# Generated by Django 5.2.1 on 2026-03-05 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfile',
            name='source_app',
            field=models.CharField(blank=True, help_text='z.B. "jds-verein"', max_length=100),
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='source_kontext',
            field=models.CharField(blank=True, help_text='z.B. "satzung", "beleg", "protokoll"', max_length=50),
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='source_ref_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='source_verein_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='source_verein_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. "Vereins-App" oder "JDS-Verein"', max_length=100)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('verein_id', models.PositiveIntegerField(blank=True, help_text='Verein-ID aus dem Vereinsprojekt (optional, für Filterung)', null=True)),
                ('verein_name', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
